# Generated by Django 5.0.6 on 2025-03-01 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookapp", "0004_tbl_masterorder_details_t_quantity_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tbl_order_details",
            name="MasterOrder_ID",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="order_details",
                to="bookapp.tbl_masterorder_details",
            ),
        ),
    ]
